name       : python-trio
version    : 0.18.0
release    : 1
source     :
    - https://github.com/python-trio/trio/archive/v0.18.0.tar.gz : 8880b7e77b73adf726df4d458c736f811a40f88bb6538f81d4f11d33f980fd3e
license    : Apache-2.0
component  : programming.python
summary    : Trio – a friendly Python library for async concurrency and I/O
description: |
    Trio – a friendly Python library for async concurrency and I/O
builddeps  :
    - pylint # check
    - python3-jedi # check
    - python-astor
    - python-async-generator
    - python-openssl
    - python-outcome
    - python-pytest
    - python-sniffio
    - python-sortedcontainers
    - python-trustme
rundeps    :
    - python-attrs
    - python-astor
    - python-async-generator
    - python-openssl
    - python-outcome
    - python-sniffio
    - python-sortedcontainers
    - python-trustme
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
