name       : python-trio
version    : 0.21.0
release    : 7
source     :
    - https://github.com/python-trio/trio/archive/refs/tags/v0.21.0.tar.gz : b37dade091c9da7b95b572643c56479c4a11596175b93ba3d6d7ff89993a40c5
homepage   : https://github.com/python-trio/trio
license    : Apache-2.0
component  : programming.python
summary    : Trio – a friendly Python library for async concurrency and I/O
description: |
    The Trio project aims to produce a production-quality, permissively licensed, async/await-native I/O library for Python. Like all async libraries, its main purpose is to help you write programs that do multiple things at the same time with parallelized I/O.
builddeps  :
    - pylint                  # check
    - python-astor            # check
    - python-async-generator  # check
    - python-jedi             # check
    - python-openssl          # check
    - python-outcome          # check
    - python-pytest           # check
    - python-sniffio          # check
    - python-sortedcontainers # check
    - python-trustme          # check
rundeps    :
    - python-async-generator
    - python-openssl
    - python-outcome
    - python-sniffio
    - python-sortedcontainers
    - python-trustme
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
