name       : python-trio
version    : 0.19.0
release    : 4
source     :
    - https://github.com/python-trio/trio/archive/refs/tags/v0.19.0.tar.gz : 453afdf9a9b128f271d7d89626c060af475cd8297b4c7d7730f0e377c359244e
homepage   : https://github.com/python-trio/trio
license    : Apache-2.0
component  : programming.python
summary    : Trio – a friendly Python library for async concurrency and I/O
description: |
    Trio – a friendly Python library for async concurrency and I/O
builddeps  :
    - pylint # check
    - python-astor
    - python-async-generator
    - python-jedi # check
    - python-openssl
    - python-outcome
    - python-pytest
    - python-sniffio
    - python-sortedcontainers
    - python-trustme
rundeps    :
    - python-attrs
    - python-astor
    - python-async-generator
    - python-openssl
    - python-outcome
    - python-sniffio
    - python-sortedcontainers
    - python-trustme
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
